name: Deploy JTL-Connector GLOBAL to Mittwald

on:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Add deploy-server to known_hosts"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ env.DEPLOYMENT_SSH_SERVER }}" >> ~/.ssh/known_hosts
        env:
          DEPLOYMENT_SSH_SERVER: p689712.mittwaldserver.info

      - name: "Deploy GLOBAL to Production (main branch)"
        if: ${{ github.ref == 'refs/heads/main' }}
        run: /usr/bin/env bash ${GITHUB_WORKSPACE}/.github/deploy/deploy.sh
        env:
          DEPLOYMENT_SSH_SERVER: p689712.mittwaldserver.info
          DEPLOYMENT_SSH_USER: p689712
          DEPLOYMENT_REPOPATH: /home/www/p689712/html/prod.jtl-connector-global/.git
          DEPLOYMENT_WORKTREE: /home/www/p689712/html/prod.jtl-connector-global
          COMPOSER_COMMAND: "/usr/local/bin/php /usr/local/bin/composer"

      - name: "Deploy GLOBAL to Testsystem (dev branch)"
        if: ${{ github.ref == 'refs/heads/dev' }}
        run: /usr/bin/env bash ${GITHUB_WORKSPACE}/.github/deploy/deploy.sh
        env:
          DEPLOYMENT_SSH_SERVER: p689712.mittwaldserver.info
          DEPLOYMENT_SSH_USER: p689712
          DEPLOYMENT_REPOPATH: /home/www/p689712/html/jtl-connector-global/.git
          DEPLOYMENT_WORKTREE: /home/www/p689712/html/jtl-connector-global
          COMPOSER_COMMAND: "/usr/local/bin/php /usr/local/bin/composer"
